[build]
  base = "."  # Ensure this points to the root of your project
  command = "make build"  # This should invoke the Makefile to build both UI and server
  publish = "ui/build"  # Correct path to the React build folder

[functions]
  directory = "server"  # Correct path to the Go serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
