# netlify.toml

[build]
  # Set the base directory for the project if needed (usually where the React app lives)
  base = "/"  # Optional, if your project is nested. Otherwise, omit this line.

  # Command to build both the React frontend and the Go backend
  command = "make build"

  # Publish directory for the React frontend build output
  publish = "/ui/build"

# Redirects for API calls to Go serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  # Set the directory where your Go serverless functions are located
  directory = "/server"

[build.environment]
  # Any environment variables needed for your build process (optional)
  NODE_ENV = "production"

# Optional headers for caching, security, etc.
[[headers]]
  for = "/ui/build/*"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=86400"
