# netlify.toml

[build]
  # Set the base directory for the project if needed (usually where the React app lives)
  base = "ui"  # Optional, if your project is nested. Otherwise, omit this line.

  # Ensure npm install is run before the build command
  command = "npm install && make build"  # Run npm install first, then run make build

  # Publish directory for the React frontend build output
  publish = "ui/build"

# Redirects for API calls to Go serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  # Corrected syntax for specifying Go function directory
  directory = "server"

[build.environment]
  # Correct format: key-value pairs for environment variables
  NODE_ENV = "production"

# Optional headers for caching, security, etc.
[[headers]]
  for = "/ui/build/*"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=86400"
