# netlify.toml
[build]
  base = "."               
  command = "go build -o ."      
  publish = "server"             
  functions = "server/functions"


[build.environment]
  GO_VERSION = "1.21"
  CGO_ENABLED = "0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200